/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package income_tax_calculator;
import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Dell
 */
public class App extends javax.swing.JFrame {
    // Global variables 
    private String name ;
    private int age;
    private int annual_income ;
    Connection con;
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        createConnection();
    }
    
    void createConnection(){
        try{
          Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tax_history_sql?zeroDateTimeBehavior=convertToNull", "root", "sql@8.0.19");
          System.out.println("Database connection success!");
        }
        catch(ClassNotFoundException ex){
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(SQLException ex){
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        age_radio = new javax.swing.ButtonGroup();
        metro_radio = new javax.swing.ButtonGroup();
        nav_panel = new javax.swing.JPanel();
        baisc_tab_btn = new javax.swing.JButton();
        inv_tab_btn = new javax.swing.JButton();
        summ_tab_btn = new javax.swing.JButton();
        bg_card = new javax.swing.JPanel();
        basic_details_card = new javax.swing.JPanel();
        basic_details_main_label = new javax.swing.JLabel();
        age_label = new javax.swing.JLabel();
        below_60_radio = new javax.swing.JRadioButton();
        bw_61_80_radio = new javax.swing.JRadioButton();
        above_81_radio = new javax.swing.JRadioButton();
        name_label = new javax.swing.JLabel();
        name_text = new javax.swing.JTextField();
        income_label = new javax.swing.JLabel();
        income_text = new javax.swing.JTextField();
        city_radio = new javax.swing.JLabel();
        metro_yes_radio = new javax.swing.JRadioButton();
        metro_no_radio = new javax.swing.JRadioButton();
        basic_details_start = new javax.swing.JButton();
        income_error_text = new javax.swing.JLabel();
        investments_card = new javax.swing.JPanel();
        investments_main_label = new javax.swing.JLabel();
        invest_ded_label = new javax.swing.JLabel();
        invest_ded_text = new javax.swing.JTextField();
        invest_health_label = new javax.swing.JLabel();
        invest_home_label = new javax.swing.JLabel();
        invest_hra_label = new javax.swing.JLabel();
        invest_edu_label = new javax.swing.JLabel();
        calculate_tax = new javax.swing.JButton();
        invest_hra_text = new javax.swing.JTextField();
        invest_health_text = new javax.swing.JTextField();
        invest_home_text = new javax.swing.JTextField();
        invest_edu_text = new javax.swing.JTextField();
        summary_card = new javax.swing.JPanel();
        summ_main_label = new javax.swing.JLabel();
        summ_tax_pay_label = new javax.swing.JLabel();
        summ_tax_inc_label = new javax.swing.JLabel();
        summ_total_inv_label = new javax.swing.JLabel();
        summ_total_inc_label = new javax.swing.JLabel();
        summ_name_label = new javax.swing.JLabel();
        summ_name_val_label = new javax.swing.JLabel();
        summ_total_inc_val_label = new javax.swing.JLabel();
        summ_total_inv_val_label = new javax.swing.JLabel();
        summ_tax_inc_val_label = new javax.swing.JLabel();
        summ_tax_pay_val_label = new javax.swing.JLabel();
        summ_home_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav_panel.setBackground(new java.awt.Color(51, 51, 51));

        baisc_tab_btn.setBackground(new java.awt.Color(153, 153, 153));
        baisc_tab_btn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        baisc_tab_btn.setText("Basic Details");
        baisc_tab_btn.setBorder(null);
        baisc_tab_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baisc_tab_btnActionPerformed(evt);
            }
        });

        inv_tab_btn.setBackground(new java.awt.Color(153, 153, 153));
        inv_tab_btn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inv_tab_btn.setText("Investments");
        inv_tab_btn.setBorder(null);
        inv_tab_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_tab_btnActionPerformed(evt);
            }
        });

        summ_tab_btn.setBackground(new java.awt.Color(153, 153, 153));
        summ_tab_btn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        summ_tab_btn.setText("Summary");
        summ_tab_btn.setBorder(null);
        summ_tab_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summ_tab_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nav_panelLayout = new javax.swing.GroupLayout(nav_panel);
        nav_panel.setLayout(nav_panelLayout);
        nav_panelLayout.setHorizontalGroup(
            nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_panelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(baisc_tab_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(inv_tab_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(summ_tab_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        nav_panelLayout.setVerticalGroup(
            nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baisc_tab_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inv_tab_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(summ_tab_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(407, Short.MAX_VALUE))
        );

        getContentPane().add(nav_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        bg_card.setBackground(new java.awt.Color(255, 255, 255));
        bg_card.setPreferredSize(new java.awt.Dimension(400, 400));
        bg_card.setLayout(new java.awt.CardLayout());

        basic_details_card.setBackground(new java.awt.Color(204, 204, 204));
        basic_details_card.setForeground(new java.awt.Color(153, 153, 153));

        basic_details_main_label.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        basic_details_main_label.setForeground(new java.awt.Color(51, 51, 51));
        basic_details_main_label.setText("Basic Details");

        age_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        age_label.setForeground(new java.awt.Color(102, 102, 102));
        age_label.setText("What is your current age?");

        below_60_radio.setBackground(new java.awt.Color(204, 204, 204));
        age_radio.add(below_60_radio);
        below_60_radio.setText("Below 60");

        bw_61_80_radio.setBackground(new java.awt.Color(204, 204, 204));
        age_radio.add(bw_61_80_radio);
        bw_61_80_radio.setText("61 to 80");

        above_81_radio.setBackground(new java.awt.Color(204, 204, 204));
        age_radio.add(above_81_radio);
        above_81_radio.setText("Above 81");

        name_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        name_label.setForeground(new java.awt.Color(102, 102, 102));
        name_label.setText("Please enter your name");

        income_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        income_label.setForeground(new java.awt.Color(102, 102, 102));
        income_label.setText("What is your yearly income?");

        income_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                income_textActionPerformed(evt);
            }
        });

        city_radio.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        city_radio.setForeground(new java.awt.Color(102, 102, 102));
        city_radio.setText("Do you live in a metropoliton city?");

        metro_yes_radio.setBackground(new java.awt.Color(204, 204, 204));
        metro_radio.add(metro_yes_radio);
        metro_yes_radio.setText("Yes");

        metro_no_radio.setBackground(new java.awt.Color(204, 204, 204));
        metro_radio.add(metro_no_radio);
        metro_no_radio.setText("No");

        basic_details_start.setBackground(new java.awt.Color(102, 102, 102));
        basic_details_start.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        basic_details_start.setForeground(new java.awt.Color(0, 51, 51));
        basic_details_start.setText("S T A R T");
        basic_details_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basic_details_startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basic_details_cardLayout = new javax.swing.GroupLayout(basic_details_card);
        basic_details_card.setLayout(basic_details_cardLayout);
        basic_details_cardLayout.setHorizontalGroup(
            basic_details_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic_details_cardLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(basic_details_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basic_details_cardLayout.createSequentialGroup()
                        .addGroup(basic_details_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(basic_details_cardLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(age_label, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(basic_details_cardLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(below_60_radio)
                                .addGap(77, 77, 77)
                                .addComponent(bw_61_80_radio)
                                .addGap(71, 71, 71)
                                .addComponent(above_81_radio))
                            .addComponent(income_label, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(basic_details_cardLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(basic_details_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(basic_details_cardLayout.createSequentialGroup()
                                        .addComponent(metro_yes_radio)
                                        .addGap(18, 18, 18)
                                        .addComponent(metro_no_radio))
                                    .addGroup(basic_details_cardLayout.createSequentialGroup()
                                        .addComponent(income_text, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(income_error_text, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(basic_details_cardLayout.createSequentialGroup()
                        .addGroup(basic_details_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(basic_details_start, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 238, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basic_details_cardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(basic_details_main_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        basic_details_cardLayout.setVerticalGroup(
            basic_details_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic_details_cardLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(basic_details_main_label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(age_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basic_details_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bw_61_80_radio)
                    .addComponent(above_81_radio)
                    .addComponent(below_60_radio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(income_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basic_details_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(income_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(income_error_text, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(city_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basic_details_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metro_yes_radio)
                    .addComponent(metro_no_radio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basic_details_start, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg_card.add(basic_details_card, "card2");

        investments_card.setBackground(new java.awt.Color(204, 204, 204));

        investments_main_label.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        investments_main_label.setForeground(new java.awt.Color(51, 51, 51));
        investments_main_label.setText("Your Investment Details");

        invest_ded_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        invest_ded_label.setForeground(new java.awt.Color(102, 102, 102));
        invest_ded_label.setText("Deductions according to u/c 80CCC and u/c 80CCD");

        invest_ded_text.setText("0");

        invest_health_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        invest_health_label.setForeground(new java.awt.Color(102, 102, 102));
        invest_health_label.setText("Health Insurance Premium according to u/s 80D");

        invest_home_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        invest_home_label.setForeground(new java.awt.Color(102, 102, 102));
        invest_home_label.setText("Interest on Home Loans according to u/s 24");

        invest_hra_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        invest_hra_label.setForeground(new java.awt.Color(102, 102, 102));
        invest_hra_label.setText("HRA Deductions according to u/s 10(13A)");

        invest_edu_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        invest_edu_label.setForeground(new java.awt.Color(102, 102, 102));
        invest_edu_label.setText("Interest on Education Loans according to u/s 80TTA");

        calculate_tax.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        calculate_tax.setText("C A L C U L A T E    T A X");
        calculate_tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_taxActionPerformed(evt);
            }
        });

        invest_hra_text.setText("0");

        invest_health_text.setText("0");

        invest_home_text.setText("0");

        invest_edu_text.setText("0");

        javax.swing.GroupLayout investments_cardLayout = new javax.swing.GroupLayout(investments_card);
        investments_card.setLayout(investments_cardLayout);
        investments_cardLayout.setHorizontalGroup(
            investments_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investments_cardLayout.createSequentialGroup()
                .addGroup(investments_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(investments_cardLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(investments_main_label, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(investments_cardLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(investments_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(investments_cardLayout.createSequentialGroup()
                                .addComponent(invest_ded_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(invest_ded_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(investments_cardLayout.createSequentialGroup()
                                .addGroup(investments_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(invest_edu_label)
                                    .addComponent(invest_home_label)
                                    .addComponent(invest_hra_label)
                                    .addComponent(invest_health_label))
                                .addGap(34, 34, 34)
                                .addGroup(investments_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(invest_health_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(invest_hra_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(invest_home_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(invest_edu_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(72, 72, 72))
            .addGroup(investments_cardLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(calculate_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        investments_cardLayout.setVerticalGroup(
            investments_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investments_cardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(investments_main_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(investments_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invest_ded_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invest_ded_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(investments_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invest_health_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invest_health_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(investments_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invest_hra_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invest_hra_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(investments_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(investments_cardLayout.createSequentialGroup()
                        .addComponent(invest_home_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(investments_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invest_edu_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invest_edu_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(invest_home_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(calculate_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        bg_card.add(investments_card, "card2");

        summary_card.setBackground(new java.awt.Color(204, 204, 204));

        summ_main_label.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        summ_main_label.setForeground(new java.awt.Color(51, 51, 51));
        summ_main_label.setText("Summary");

        summ_tax_pay_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        summ_tax_pay_label.setForeground(new java.awt.Color(102, 102, 102));
        summ_tax_pay_label.setText("Tax Payable");

        summ_tax_inc_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        summ_tax_inc_label.setForeground(new java.awt.Color(102, 102, 102));
        summ_tax_inc_label.setText("Taxable Income");

        summ_total_inv_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        summ_total_inv_label.setForeground(new java.awt.Color(102, 102, 102));
        summ_total_inv_label.setText("Total Investments");

        summ_total_inc_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        summ_total_inc_label.setForeground(new java.awt.Color(102, 102, 102));
        summ_total_inc_label.setText("Total Income");

        summ_name_label.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        summ_name_label.setForeground(new java.awt.Color(102, 102, 102));
        summ_name_label.setText("Name");

        summ_name_val_label.setText("-");

        summ_total_inc_val_label.setText("-");

        summ_total_inv_val_label.setText("-");

        summ_tax_inc_val_label.setText("-");

        summ_tax_pay_val_label.setText("-");

        summ_home_btn.setText("H O M E");
        summ_home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summ_home_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout summary_cardLayout = new javax.swing.GroupLayout(summary_card);
        summary_card.setLayout(summary_cardLayout);
        summary_cardLayout.setHorizontalGroup(
            summary_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summary_cardLayout.createSequentialGroup()
                .addGroup(summary_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(summary_cardLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(summ_main_label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(summary_cardLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(summary_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(summ_tax_pay_label)
                            .addComponent(summ_tax_inc_label)
                            .addComponent(summ_total_inv_label)
                            .addComponent(summ_total_inc_label)
                            .addComponent(summ_name_label))
                        .addGap(81, 81, 81)
                        .addGroup(summary_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(summ_total_inv_val_label, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(summ_total_inc_val_label, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(summ_name_val_label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(summary_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(summ_tax_pay_val_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(summ_tax_inc_val_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(summary_cardLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(summ_home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        summary_cardLayout.setVerticalGroup(
            summary_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summary_cardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(summ_main_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(summary_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summ_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(summ_name_val_label))
                .addGap(18, 18, 18)
                .addGroup(summary_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summ_total_inc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(summ_total_inc_val_label))
                .addGap(18, 18, 18)
                .addGroup(summary_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summ_total_inv_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(summ_total_inv_val_label))
                .addGap(18, 18, 18)
                .addGroup(summary_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(summ_tax_inc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(summ_tax_inc_val_label))
                .addGap(18, 18, 18)
                .addGroup(summary_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(summ_tax_pay_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(summ_tax_pay_val_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(summ_home_btn)
                .addGap(41, 41, 41))
        );

        bg_card.add(summary_card, "card2");

        getContentPane().add(bg_card, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 590, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baisc_tab_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baisc_tab_btnActionPerformed
        // TODO add your handling code here:
        bg_card.removeAll();
        bg_card.repaint();
        bg_card.revalidate();
             
        bg_card.add(basic_details_card);
        bg_card.repaint();
        bg_card.revalidate();
    }//GEN-LAST:event_baisc_tab_btnActionPerformed

    private void inv_tab_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_tab_btnActionPerformed
        // TODO add your handling code here:
        bg_card.removeAll();
        bg_card.repaint();
        bg_card.revalidate();
            
        bg_card.add(investments_card);
        bg_card.repaint();
        bg_card.revalidate();
    }//GEN-LAST:event_inv_tab_btnActionPerformed

    private void summ_tab_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summ_tab_btnActionPerformed
        // TODO add your handling code here:
        bg_card.removeAll();
        bg_card.repaint();
        bg_card.revalidate();
             
        bg_card.add(summary_card);
        bg_card.repaint();
        bg_card.revalidate();
    }//GEN-LAST:event_summ_tab_btnActionPerformed

    private void income_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_income_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_income_textActionPerformed

    private void basic_details_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basic_details_startActionPerformed
        // TODO add your handling code here:
        name = name_text.getText();
        annual_income = Integer.parseInt(income_text.getText());
        
        
        //System.out.println(name+" "+annual_income);
        
        bg_card.removeAll();
        bg_card.repaint();
        bg_card.revalidate();
                
        bg_card.add(investments_card);
        bg_card.repaint();
        bg_card.revalidate();
        
        
    }//GEN-LAST:event_basic_details_startActionPerformed

    private void calculate_taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_taxActionPerformed
        // TODO add your handling code here:
        summ_name_val_label.setText(name);
        int ded = Integer.parseInt(invest_ded_text.getText());
        int health = Integer.parseInt(invest_health_text.getText());
        int hra = Integer.parseInt(invest_hra_text.getText());
        int home = Integer.parseInt(invest_home_text.getText());
        int edu = Integer.parseInt(invest_edu_text.getText());
        double tax_pay, tax_income, total_inv;
        
        if( ded > 200000 ) ded = 200000;
        
        if(below_60_radio.isSelected()){
            if(health > 75000 ) health = 75000;
        }
        else{
            if(health > 100000 ) health = 100000;
        }
        
        if(metro_yes_radio.isSelected()){
            if( hra > (annual_income/2) ) hra = (annual_income/2); 
        }
        else{
            if( hra > (2*annual_income/5) ) hra = (2*annual_income/5);
        }
        
        if(home > 200000) home = 200000;
            
        total_inv = ded + health + edu + home + hra ;
        tax_income = annual_income - total_inv ;
        if( tax_income < 0)  tax_income = 0 ;
        
        // Calculating tax_payable 
        if(below_60_radio.isSelected()){
            if(tax_income <= 250000) tax_pay =0;
            else if(tax_income >=250001) tax_pay = 0.05*tax_income;
            else if(tax_income >= 500001.0) tax_pay = 12500.0 + 0.2*(tax_income-500000.0);
            else tax_pay = 112500.0 + 0.3*(tax_income-1000000.0);
            System.out.println("<60 "+tax_pay);
        }
        else if(bw_61_80_radio.isSelected()){
            if(tax_income <= 300000) tax_pay =0;
            else if(tax_income >=300001) tax_pay = .05*tax_income;
            else if(tax_income >= 500001) tax_pay = 10000 + .2*(tax_income-500000);
            else tax_pay = 110000 + 0.3*(tax_income-1000000);
            System.out.println("61-80 "+tax_pay);
        }
        else{
            if(tax_income <= 500000) tax_pay =0;
            else if(tax_income >= 500001) tax_pay = .2*(tax_income-500000);
            else tax_pay = 100000 + 0.3*(tax_income-1000000);
            System.out.println(">81 "+tax_pay);
        }
        
        
        System.out.println(tax_pay);
        summ_tax_pay_val_label.setText(String.valueOf(tax_pay));
        summ_total_inv_val_label.setText(String.valueOf(total_inv));
        summ_total_inc_val_label.setText(String.valueOf(annual_income));
        summ_tax_inc_val_label.setText(String.valueOf(tax_income));
        
        
        bg_card.removeAll();
        bg_card.repaint();
        bg_card.revalidate();
        
        bg_card.add(summary_card);
        bg_card.repaint();
        bg_card.revalidate();
        try{
            java.util.Date date = new java.util.Date();
            java.sql.Timestamp timestamp = new java.sql.Timestamp(date.getTime());
            
            PreparedStatement ps =con.prepareStatement("INSERT INTO tax_history VALUES(?,?,?,?,?,?)");
            ps.setTimestamp(1, timestamp);
            ps.setString(2,name);
            ps.setFloat(3,(float)annual_income);
            ps.setFloat(4,(float)total_inv);
            ps.setFloat(5,(float)tax_income);
            ps.setFloat(6,(float)tax_pay);
            ps.execute();
            ps.close();
        }
        catch(SQLException ex){
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Tax Payable = "+tax_pay+"\nTotal Investment = "+total_inv+"\nTax Income = "+tax_income);
    }//GEN-LAST:event_calculate_taxActionPerformed

    private void summ_home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summ_home_btnActionPerformed
        // TODO add your handling code here:
        new AIndex().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_summ_home_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    //void createConnection(){
        
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton above_81_radio;
    private javax.swing.JLabel age_label;
    private javax.swing.ButtonGroup age_radio;
    private javax.swing.JButton baisc_tab_btn;
    private javax.swing.JPanel basic_details_card;
    private javax.swing.JLabel basic_details_main_label;
    private javax.swing.JButton basic_details_start;
    private javax.swing.JRadioButton below_60_radio;
    private javax.swing.JPanel bg_card;
    private javax.swing.JRadioButton bw_61_80_radio;
    private javax.swing.JButton calculate_tax;
    private javax.swing.JLabel city_radio;
    private javax.swing.JLabel income_error_text;
    private javax.swing.JLabel income_label;
    private javax.swing.JTextField income_text;
    private javax.swing.JButton inv_tab_btn;
    private javax.swing.JLabel invest_ded_label;
    private javax.swing.JTextField invest_ded_text;
    private javax.swing.JLabel invest_edu_label;
    private javax.swing.JTextField invest_edu_text;
    private javax.swing.JLabel invest_health_label;
    private javax.swing.JTextField invest_health_text;
    private javax.swing.JLabel invest_home_label;
    private javax.swing.JTextField invest_home_text;
    private javax.swing.JLabel invest_hra_label;
    private javax.swing.JTextField invest_hra_text;
    private javax.swing.JPanel investments_card;
    private javax.swing.JLabel investments_main_label;
    private javax.swing.JRadioButton metro_no_radio;
    private javax.swing.ButtonGroup metro_radio;
    private javax.swing.JRadioButton metro_yes_radio;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField name_text;
    private javax.swing.JPanel nav_panel;
    private javax.swing.JButton summ_home_btn;
    private javax.swing.JLabel summ_main_label;
    private javax.swing.JLabel summ_name_label;
    private javax.swing.JLabel summ_name_val_label;
    private javax.swing.JButton summ_tab_btn;
    private javax.swing.JLabel summ_tax_inc_label;
    private javax.swing.JLabel summ_tax_inc_val_label;
    private javax.swing.JLabel summ_tax_pay_label;
    private javax.swing.JLabel summ_tax_pay_val_label;
    private javax.swing.JLabel summ_total_inc_label;
    private javax.swing.JLabel summ_total_inc_val_label;
    private javax.swing.JLabel summ_total_inv_label;
    private javax.swing.JLabel summ_total_inv_val_label;
    private javax.swing.JPanel summary_card;
    // End of variables declaration//GEN-END:variables
}
